spring:
  datasource:
    hikari:
      a-database:
        jdbc-url: jdbc:mysql://localhost:3306/spring_batch
        username: root
        password: 1q2w3e!
        driver-class-name: com.mysql.jdbc.Driver
      b-database:
        jdbc-url: jdbc:mysql://localhost:12020/spring_batch
        username: root
        password: 1q2w3e!
        driver-class-name: com.mysql.jdbc.Driver
      c-database:
        jdbc-url: jdbc:mysql://localhost:12021/spring_batch
        username: root
        password: 1q2w3e!
        driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
